### PR TITLE
Python

### PR DESCRIPTION
**Pull request by hanslovsky**
- cherry-picked commits from https://github.com/hanslovsky/jrun.py
 - tested on Linux
 - should probably test if works as previously, especially
    - shortcut expansion
    - auto-completion of abbreviated classes ('@' notation)
 - install via `pip install`

### CODE REVIEW

**Comment by hanslovsky** [comment]
As of now, `+` to define secondary endpoints is not supported in the python port yet. I will address this in the following way:
 - first endpoint is `main` endpoint that holds main class and `mainClass` will be stored in a subdirectory thereof that is identified by the secondary endpoints. Note that, even though something like `groupA:artifactA+groupB:artifactB+groupC:artifactC` would be equivalent to `groupA:artifactA+groupC:artifactC+groupB:artifactB`, those two endpoint definitions would be stored in separate folders, which would not be a big deal because that is mostly just the `mainClass` file. A possible workaround is splitting at `+` and sort the resulting array (excluding the `main` endpoint) but that seems unnecessary.
 - The jars for each endpoint (both `main` and secondary) reside in the workspace defined by that endpoint alone and a look-up for these jars will happen accordingly. I plan on not using wildcard for the secondary jars, because I already have code for that (producing wild card instead would not be much work, though).

**Comment by hanslovsky** [comment]
Secondary endpoint support added in b118344. Against my initial intuition, using wildcard for the secondary classpaths turned out to be easier.

**Comment by hanslovsky** [comment]
@ctrueden I really like the secondary endpoint option. Users can now [use any `slf4j` logging in my paintera package on conda](https://github.com/saalfeldlab/paintera/blob/master/README.md#run):
```
PAINTERA_SLF4J_BINDING=groupId:artifactId[:version] paintera
```

**Comment by hanslovsky** [comment]
I just tested all the examples in `README.md` and they all worked.

**Comment by hanslovsky** [comment]
@ctrueden I changed the python jrun as discussed [on gitter](https://gitter.im/scijava/scijava-common?at=5b86b95c94f8164c17b88cc9). I tested all the [examples](https://github.com/ctrueden/jrun#examples) and all of them work. Only the first example throws a, probably unrelated, exception, but then continues into the python interpreter:
```
$ jrun org.python:jython-standalone
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at org.python.jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
        at org.python.jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
        at org.python.jline.UnixTerminal.<init>(UnixTerminal.java:65)
        at org.python.jline.UnixTerminal.<init>(UnixTerminal.java:50)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.python.jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
        at org.python.jline.TerminalFactory.create(TerminalFactory.java:102)
        at org.python.jline.TerminalFactory.get(TerminalFactory.java:186)
        at org.python.jline.TerminalFactory.get(TerminalFactory.java:192)
        at org.python.jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
        at org.python.util.JLineConsole.install(JLineConsole.java:107)
        at org.python.core.Py.installConsole(Py.java:1744)
        at org.python.core.PySystemState.initConsole(PySystemState.java:1269)
        at org.python.core.PySystemState.doInitialize(PySystemState.java:1119)
        at org.python.core.PySystemState.initialize(PySystemState.java:1033)
        at org.python.core.PySystemState.initialize(PySystemState.java:989)
        at org.python.core.PySystemState.initialize(PySystemState.java:984)
        at org.python.util.jython.run(jython.java:263)
        at org.python.util.jython.main(jython.java:142)

Jython 2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_172
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by hanslovsky** [comment]
@ctrueden What's the status on this?

**Comment by ctrueden** [comment]
Sorry for the long delay, @hanslovsky. Aside from being too busy, my main hesitation in merging this was that it breaks all existing symlinks to the `jrun` executable. But it seems unavoidable, so I'll just go ahead now.

I'll test it on my system post-merge, update the docs, and so forth. I'll follow up with you if I find any grievous issues.

**Comment by ctrueden** [comment]
@hanslovsky I updated the README, but have some questions:

1. What is the minimum required version of Python?
2. How do you launch the Python version from the CLI? I tried `python jrun` but it says `can't find '__main__' module in 'jrun'`.
3. As such, could you please add some installation instructions for the Python version where it now says `<INSTRUCTIONS COMING SOON>`?

**Comment by hanslovsky** [comment]
1. I tested with python 3.6 and 3.7. I have doubts that it will work with python 2.7 and I think we [should not support python 2](https://pythonclock.org/)
 2. You will have to install via pip or conda first:
 ```
# via pip from jrun root directory:
pip install . # requires sudo
pip install . --user # to install into $HOME/.local/{bin,lib} (or somewhere else on Windows)
pip install . --prefix=$PREFIX # to install into $PREFIX/{bin,lib}
# or from conda:
conda install -c hanslovsky python=3.6 jrun
```
 3. I will add the instructions from (2) to the appropriate section

**Comment by hanslovsky** [comment]
> Do you think it is worth adding this to the repository?

I do not have a strong opinion as I usually don't run python stuff like that (as you could probably tell from the missing `__main__.py`). It doesn't add any complexity, though, so I'd say, let's add it.

**Comment by hanslovsky** [comment]
Also, we should probably create a conda package on conda-forge instead of my channel, eventually.

**Pull request merged**
